name: Auto approve

on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2
        if: github.actor == 'ampprojectbot' && (startsWith(github.ref_name == 'promote-') || startsWith(github.ref_name == 'cherry-pick-'))
        with:
          github-token: '${{ github.token }}'
