name: Auto approve

on:
  pull_request:
    types:
      - auto_merge_enabled

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2
        if: github.actor == 'ampprojectbot'
        with:
          github-token: '${{ github.token }}'
